"""add seat location info to event info table

Revision ID: 0fee087bbbf3
Revises: 1fe6f7477c50
Create Date: 2024-11-26 09:41:07.978121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fee087bbbf3'
down_revision = '1fe6f7477c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('location', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('row', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_info', 'note')
    op.drop_column('event_info', 'quantity')
    op.drop_column('event_info', 'row')
    op.drop_column('event_info', 'location')
    # ### end Alembic commands ###
