"""uncomment averages

Revision ID: 10c4e9abd66d
Revises: ffc655aa71c7
Create Date: 2024-12-01 11:23:59.627472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c4e9abd66d'
down_revision = 'ffc655aa71c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('average_denominator', sa.Integer(), nullable=True))
    op.add_column('event_info', sa.Column('average_lowest_price', sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_info', 'average_lowest_price')
    op.drop_column('event_info', 'average_denominator')
    # ### end Alembic commands ###
