"""empty message

Revision ID: 12f61bf8f3c0
Revises: 8ad6f7f22f2a
Create Date: 2025-08-07 18:22:20.824607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12f61bf8f3c0'
down_revision = '8ad6f7f22f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_alert', sa.Column('price_number', sa.Numeric(scale=2), nullable=True))
    op.add_column('category_alert', sa.Column('price_percent', sa.Numeric(scale=2), nullable=True))
    op.add_column('category_alert', sa.Column('ticket_location', sa.String(), nullable=True))
    op.add_column('category_alert', sa.Column('ticket_row', sa.String(), nullable=True))
    op.add_column('category_alert', sa.Column('ticket_quantity', sa.String(), nullable=True))
    op.add_column('category_alert', sa.Column('ticket_note', sa.String(), nullable=True))
    op.add_column('category_alert', sa.Column('notification_method', sa.String(), nullable=False, server_default='email'))
    op.add_column('category_alert', sa.Column('created_on', sa.Date(), nullable=True))
    op.alter_column('category_alert', 'show_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('category_alert', 'send_email')
    op.drop_column('category_alert', 'send_push')
    op.drop_column('category_alert', 'send_sms')
    op.add_column('event_alert', sa.Column('price_number', sa.Numeric(scale=2), nullable=True))
    op.add_column('event_alert', sa.Column('price_percent', sa.Numeric(scale=2), nullable=True))
    op.add_column('event_alert', sa.Column('ticket_location', sa.String(), nullable=True))
    op.add_column('event_alert', sa.Column('ticket_row', sa.String(), nullable=True))
    op.add_column('event_alert', sa.Column('ticket_quantity', sa.String(), nullable=True))
    op.add_column('event_alert', sa.Column('ticket_note', sa.String(), nullable=True))
    op.add_column('event_alert', sa.Column('notification_method', sa.String(), nullable=False, server_default='email'))
    op.add_column('event_alert', sa.Column('created_on', sa.Date(), nullable=True))
    op.alter_column('event_alert', 'show_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('event_alert', 'send_email')
    op.drop_column('event_alert', 'send_push')
    op.drop_column('event_alert', 'send_sms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_alert', sa.Column('send_sms', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event_alert', sa.Column('send_push', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event_alert', sa.Column('send_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('event_alert', 'show_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.drop_column('event_alert', 'created_on')
    op.drop_column('event_alert', 'notification_method')
    op.drop_column('event_alert', 'ticket_note')
    op.drop_column('event_alert', 'ticket_quantity')
    op.drop_column('event_alert', 'ticket_row')
    op.drop_column('event_alert', 'ticket_location')
    op.drop_column('event_alert', 'price_percent')
    op.drop_column('event_alert', 'price_number')
    op.add_column('category_alert', sa.Column('send_sms', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('category_alert', sa.Column('send_push', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('category_alert', sa.Column('send_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('category_alert', 'show_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.drop_column('category_alert', 'created_on')
    op.drop_column('category_alert', 'notification_method')
    op.drop_column('category_alert', 'ticket_note')
    op.drop_column('category_alert', 'ticket_quantity')
    op.drop_column('category_alert', 'ticket_row')
    op.drop_column('category_alert', 'ticket_location')
    op.drop_column('category_alert', 'price_percent')
    op.drop_column('category_alert', 'price_number')
    # ### end Alembic commands ###
