"""add notification method to preferences tables

Revision ID: 1fe6f7477c50
Revises: 360187e619e4
Create Date: 2024-11-22 12:40:14.317083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe6f7477c50'
down_revision = '360187e619e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_preference', sa.Column('send_email', sa.Boolean(), nullable=True))
    op.add_column('category_preference', sa.Column('send_sms', sa.Boolean(), nullable=True))
    op.add_column('category_preference', sa.Column('send_push', sa.Boolean(), nullable=True))
    op.add_column('event_preference', sa.Column('send_email', sa.Boolean(), nullable=True))
    op.add_column('event_preference', sa.Column('send_sms', sa.Boolean(), nullable=True))
    op.add_column('event_preference', sa.Column('send_push', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_preference', 'send_push')
    op.drop_column('event_preference', 'send_sms')
    op.drop_column('event_preference', 'send_email')
    op.drop_column('category_preference', 'send_push')
    op.drop_column('category_preference', 'send_sms')
    op.drop_column('category_preference', 'send_email')
    # ### end Alembic commands ###
