"""add closed bool to event table

Revision ID: 210d40ac7a10
Revises: 726cdd455998
Create Date: 2024-12-22 10:15:25.268797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210d40ac7a10'
down_revision = '726cdd455998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'closed')
    # ### end Alembic commands ###
