"""add todaytix cat id to event table

Revision ID: 360187e619e4
Revises: e65217eafd78
Create Date: 2024-11-20 19:31:37.991995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360187e619e4'
down_revision = 'e65217eafd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('todaytix_category_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'todaytix_category_id')
    # ### end Alembic commands ###
