"""empty message

Revision ID: 62095764e486
Revises: add_weekday_to_alerts
Create Date: 2025-08-11 22:14:22.324973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62095764e486'
down_revision = 'add_weekday_to_alerts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sms_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sms_consent')
    # ### end Alembic commands ###
