"""add seat location

Revision ID: 726cdd455998
Revises: 10c4e9abd66d
Create Date: 2024-12-02 05:03:24.523831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726cdd455998'
down_revision = '10c4e9abd66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('location', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('row', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_info', 'note')
    op.drop_column('event_info', 'quantity')
    op.drop_column('event_info', 'row')
    op.drop_column('event_info', 'location')
    # ### end Alembic commands ###
