"""empty message

Revision ID: 8ad6f7f22f2a
Revises: 938a786ec29a
Create Date: 2025-03-23 16:08:04.307022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad6f7f22f2a'
down_revision = '938a786ec29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_venue_region_id_region'), 'venue', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_venue_region_id_region'), 'venue', type_='foreignkey')
    op.drop_column('venue', 'region_id')
    # ### end Alembic commands ###
