"""empty message

Revision ID: 938a786ec29a
Revises: 725f2be0233c
Create Date: 2025-03-23 16:04:33.281220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938a786ec29a'
down_revision = '725f2be0233c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###
