"""add stubhub_venue_id to venue table

Revision ID: 969663a43a8d
Revises: d464fe7f23e3
Create Date: 2024-10-01 11:15:36.589774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969663a43a8d'
down_revision = 'd464fe7f23e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('stubhub_venue_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'stubhub_venue_id')
    # ### end Alembic commands ###
