"""empty message

Revision ID: acde7a8ea909
Revises: 12f61bf8f3c0
Create Date: 2025-08-07 18:38:09.076369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acde7a8ea909'
down_revision = '12f61bf8f3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_alert', 'price')
    op.drop_column('event_alert', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_alert', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('category_alert', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
