"""build database

Revision ID: bfcd671bd96d
Revises: 
Create Date: 2024-10-01 08:33:13.610997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcd671bd96d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('seatplan_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue'))
    )
    op.create_table('category_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('show_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_category_preference_category_id_category')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_category_preference_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_preference'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('lottery_url', sa.String(), nullable=True),
    sa.Column('show_duration', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_event_category_id_category')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_event_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('event_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_weekday', sa.Date(), nullable=True),
    sa.Column('formatted_date', sa.Date(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_info_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_info'))
    )
    op.create_table('event_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('show_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_preference_event_id_event')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_preference_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_preference'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_preference')
    op.drop_table('event_info')
    op.drop_table('event')
    op.drop_table('category_preference')
    op.drop_table('venue')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('category')
    # ### end Alembic commands ###
